version: "2"
services:
  auth_service:
    build: ./auth_service
    container_name: auth_service
    restart: always
    working_dir: /app
    ports:
      - "3002:3002"
    expose:
      - "3002"
    volumes:
      - ./auth_service:/app
  gw_service:
    build: ./gw_service
    container_name: gw_service
    restart: always
    working_dir: /app
    ports:
      - "3001:3001"
    expose:
      - "3001"
    volumes:
      - ./gw_service:/app
  fe01:
    build: ./fe01
    container_name: fe01
    restart: always
    working_dir: /app
    ports:
      - "3000:3000"
    expose:
      - "3000"
    volumes:
      - ./fe01:/app
      - v1:/app/node_modules
    command: "npm run start"
  mysql01:
    platform: linux/x86_64
    image: mysql:5.7
    volumes:
      - "./.mysql-data/db:/var/lib/mysql"
    restart: always
    ports:
      - 3307:3306
    expose:
      - "3307"
    environment:
      MYSQL_ROOT_PASSWORD: 123qwe
      MYSQL_DATABASE: mysql01
      MYSQL_USER: mysql01
      MYSQL_PASSWORD: 123qwe
volumes:
  v1:
    external: true
