version: "2"
services:
  auth_service:
    build: ./auth_service
    container_name: auth_service
    restart: always
    working_dir: /app
    ports:
      - "3002:3002"
    expose:
      - "3002"
    volumes:
      - ./auth_service:/app
  gw_service:
    build: ./gw_service
    container_name: gw_service
    restart: always
    working_dir: /app
    ports:
      - "3001:3001"
    expose:
      - "3001"
    volumes:
      - ./gw_service:/app
  fe01:
    build: ./fe01
    container_name: fe01
    restart: always
    working_dir: /app
    ports:
      - "3000:3000"
    expose:
      - "3000"
    volumes:
      - ./fe01:/app
      - v1:/app/node_modules
    command: "npm run start"
volumes:
  v1:
    external: true
